annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-secret-env: ""
  vault.hashicorp.com/agent-inject-file-env: "env"
  vault.hashicorp.com/agent-inject-template-env: |
    {{- with secret "warbler/mongo" -}}
    export DB_USER="{{ .Data.data.username }}"
    export DB_PASSWORD="{{ .Data.data.password }}"
    export DB_HOST="{{ .Data.data.host }}"
    export DB_PORT="27017"
    {{- end -}}
  vault.hashicorp.com/role: warbler-k8s
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/tls-skip-verify: "true"
